version: "3.8"

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    volumes:
     - journal_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
  api:
    container_name: api
    image: aikido-api:0.1
    build: ./backend
    command: bash -c "
      python src/manage.py migrate &&
      python src/manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - media:/app/src/media
    depends_on:
      - db
  web:
    container_name: web
    image: aikido-web:0.1
    build: ./frontend
    command: npm run dev
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - api

volumes:
  journal_data:
  media:
