# Generated by Django 5.0.4 on 2024-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calendarevent_googletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
